name: DEpoP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  deploy:
    env:
      reponame: nginx-configuration
    runs-on: ubuntu-latest
    steps:
      - name: syncronize
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.SSH_USER }}
            if [ ! -d "nginx-configuration" ]; then
                git clone https://github.com/Shariyl-Corporation/nginx-configuration
            fi

            cd nginx-configuration
            git pull

            doas /bin/cp nginx.conf -rf /etc/nginx/nginx.conf
            doas /bin/cp sites-enabled -rf /etc/nginx/

            doas systemctl restart nginx

